# SPDX-FileCopyrightText: The helm-charts Authors
# SPDX-License-Identifier: 0BSD

{{- if include "stageset.scaling" . }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stageset.name" . }}
  namespace: {{ include "stageset.namespace" . }}
  labels:
    {{- include "stageset.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "stageset.selectorLabels" . | nindent 6 }}
{{- end }}
