# SPDX-FileCopyrightText: The helm-charts Authors
# SPDX-License-Identifier: 0BSD

{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stageset.name" . }}-metrics
  namespace: {{ include "stageset.namespace" . }}
  labels:
    {{- include "stageset.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "stageset.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespaceSelector:
    matchNames:
      - {{ include "stageset.namespace" . }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
