# SPDX-FileCopyrightText: The helm-charts Authors
# SPDX-License-Identifier: 0BSD

{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stageset.name" . }}-webhook
  namespace: {{ include "stageset.namespace" . }}
  labels:
    {{- include "stageset.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "stageset.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
{{- end }}
