#!/usr/bin/env bash
# SPDX-FileCopyrightText: The helm-charts Authors
# SPDX-License-Identifier: 0BSD
#
# Generate charts/joi/tests/libraries-generated_test.yaml from the
# jsonnet-oci-images manifest (libraries.json on stdin or $1) — the same single
# source of truth that hack/gen-joi-values.sh consumes. For every library it
# emits a helm-unittest case that enables just that library and asserts the
# rendered OCIRepository (oci:// url + tag) and JsonnetLibrary (name + sourceRef).
# Run by .github/workflows/sync-joi.yml alongside the values regeneration so a
# new upstream library gains per-library test coverage with zero hand-editing.
# libraries.json -> values.yaml -> this test file is one automated path, so the
# generated cases can never drift from the shipped library set.
#
#   curl -fsSL <raw libraries.json> | hack/gen-joi-tests.sh > charts/joi/tests/libraries-generated_test.yaml
set -euo pipefail
manifest="${1:-/dev/stdin}"

cat <<'EOF'
# SPDX-FileCopyrightText: The helm-charts Authors
# SPDX-License-Identifier: 0BSD
#
# GENERATED by hack/gen-joi-tests.sh from the jsonnet-oci-images manifest.
# Do not hand-edit; it is regenerated by sync-joi.yml alongside values.yaml.
# One case per JOI library asserts its OCIRepository + JsonnetLibrary render.
# Hand-written logic tests (closure expansion, mirror, namespace, custom entry)
# live in joi_test.yaml and stay there.
suite: test every joi library renders its OCIRepository + JsonnetLibrary
templates:
  - templates/ocirepository.yaml
  - templates/jsonnetlibrary.yaml
tests:
EOF

# Each manifest entry -> one case enabling just that library. The image is
# ghcr.io/metio/joi-<org>-<repo>, matching hack/gen-joi-values.sh. sort_by(.name)
# keeps the output deterministic so regeneration is idempotent.
jq -r '
  sort_by(.name)[]
  | ("ghcr.io/metio/joi-" + .org + "-" + .repo) as $image
  | "  - it: renders the OCIRepository and JsonnetLibrary for \(.name)\n"
  + "    set:\n"
  + "      libraries.\(.name).enabled: true\n"
  + "    documentSelector:\n"
  + "      path: metadata.name\n"
  + "      value: \(.name)\n"
  + "    asserts:\n"
  + "      - equal:\n"
  + "          path: kind\n"
  + "          value: OCIRepository\n"
  + "        template: templates/ocirepository.yaml\n"
  + "      - equal:\n"
  + "          path: spec.url\n"
  + "          value: oci://\($image)\n"
  + "        template: templates/ocirepository.yaml\n"
  + "      - equal:\n"
  + "          path: spec.ref.tag\n"
  + "          value: latest\n"
  + "        template: templates/ocirepository.yaml\n"
  + "      - equal:\n"
  + "          path: kind\n"
  + "          value: JsonnetLibrary\n"
  + "        template: templates/jsonnetlibrary.yaml\n"
  + "      - equal:\n"
  + "          path: metadata.name\n"
  + "          value: \(.name)\n"
  + "        template: templates/jsonnetlibrary.yaml\n"
  + "      - equal:\n"
  + "          path: spec.sourceRef.kind\n"
  + "          value: OCIRepository\n"
  + "        template: templates/jsonnetlibrary.yaml\n"
  + "      - equal:\n"
  + "          path: spec.sourceRef.name\n"
  + "          value: \(.name)\n"
  + "        template: templates/jsonnetlibrary.yaml"
' "$manifest"
