#!/usr/bin/env bash
# SPDX-FileCopyrightText: The helm-charts Authors
# SPDX-License-Identifier: 0BSD
#
# Generate charts/joi/values.yaml from the jsonnet-oci-images manifest
# (libraries.json on stdin or $1) — the single source of truth the JOI build
# pipeline produces. Run by .github/workflows/sync-joi.yml so a new upstream
# library flows into the chart with zero hand-editing. Image tags are always
# `latest`; the consumer selects a version in the import path. Every library
# ships disabled — operators enable exactly the ones they need.
#
#   curl -fsSL <raw libraries.json> | hack/gen-joi-values.sh > charts/joi/values.yaml
set -euo pipefail
manifest="${1:-/dev/stdin}"

# Nothing is enabled by default; operators opt in per library. An empty set
# keeps the generated values.yaml a pure catalog, so a stock install renders no
# OCIRepository/JsonnetLibrary at all.
enabled_set=" "

cat <<'EOF'
# SPDX-FileCopyrightText: The helm-charts Authors
# SPDX-License-Identifier: 0BSD
#
# GENERATED by hack/gen-joi-values.sh from the jsonnet-oci-images manifest.
# Do not hand-edit the `libraries` map; it is regenerated by sync-joi.yml. Every
# library ships disabled — enable the ones you need. Only the non-library
# settings below are policy.

# Namespace the OCIRepository + JsonnetLibrary objects land in (release ns when empty).
namespace: ""

# Internal registry mirror for the JOI OCI artifacts (rewrites the registry host).
registryMirror: ""

# dockerconfigjson Secret for authenticated (private-mirror) pulls.
imagePullSecret: ""

# @schema
# type: string
# pattern: ^([0-9]+(ns|us|ms|s|m|h))+$
# @schema
# OCIRepository re-pull cadence (a moved `latest` tag is picked up here).
# Accepts composite Go durations (e.g. 1h30m), matching source-controller.
interval: 60m

# One entry per JOI image. Pick the LIBRARY version in the import path, e.g.
# `import 'github.com/jsonnet-libs/k8s-libsonnet/1.34/main.libsonnet'` or
# `.../latest/main.libsonnet`. `path: ""` exposes the whole vendor tree. The
# `tag` defaults to `latest` (moving); set it to a dated JOI snapshot
# (e.g. `2026.6.16`) to pin the image for reproducible pulls.
#
# @schema
# additionalProperties: true
# @schema
libraries:
EOF

# Each manifest entry -> a library block; image is ghcr.io/metio/joi-<org>-<repo>.
jq -r --arg en "$enabled_set" '
  sort_by(.name)[]
  | (" " + .name + " ") as $needle
  | (if ($en | contains($needle)) then "true" else "false" end) as $e
  | ("[" + ((.closure // []) | join(", ")) + "]") as $clo
  | "  \(.name):\n    enabled: \($e)\n    image: ghcr.io/metio/joi-\(.org)-\(.repo)\n    tag: latest\n    path: \"\"\n    # libraries this one imports; auto-enabled with it\n    closure: \($clo)"
' "$manifest"
