# SPDX-FileCopyrightText: The helm-charts Authors
# SPDX-License-Identifier: 0BSD
# Operator mode with the in-pod self-signed webhook cert machinery.
operator:
  enabled: true
  defaultServiceAccount: default
  webhook:
    enabled: true
    certMode: self-signed
